{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hitl-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hitl-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hitl-ui.selectorLabels" . | nindent 4 }}
{{- end }}
